# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeKit < Formula
  desc "CLI tool for bootstrapping Claude Code projects with best-practice templates"
  homepage "https://github.com/adrien-barret/claude-kit"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.3.0/claude-kit-v0.3.0-darwin-amd64.zip"
      sha256 "d8f530580b21d2693ab9dbdb95d66b80cc44058591f6f8d76eac3c9c95c44c75"

      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.3.0/claude-kit-v0.3.0-darwin-arm64.zip"
      sha256 "518f936b5f4dbaa24c4a742bcb73da4188359c9f4f00f35196c283db32221679"

      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.3.0/claude-kit-v0.3.0-linux-amd64.zip"
      sha256 "1bb5af9b7addb798a1fa87930fa27697eb026532d73b379b60b73157d371a453"
      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.3.0/claude-kit-v0.3.0-linux-arm64.zip"
      sha256 "704cebd48ce247fbebff1d96ee1c1b41e7fd90dac5b20c0d6493e418f1b6bdc5"
      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
  end

  test do
    system "#{bin}/ck", "version"
  end
end
