# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeKit < Formula
  desc "CLI tool for bootstrapping Claude Code projects with best-practice templates"
  homepage "https://github.com/adrien-barret/claude-kit"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.2.5/claude-kit-v0.2.5-darwin-amd64.zip"
      sha256 "fb3fa729382ce28bff05277127d0c4af7d173cc275ab8f033c129d54d1235c4f"

      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.2.5/claude-kit-v0.2.5-darwin-arm64.zip"
      sha256 "6925533025ccf9e267d27cec7af24703ce53d11edbec93283b6170a128358238"

      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.2.5/claude-kit-v0.2.5-linux-amd64.zip"
      sha256 "126aef53338237762059033c4620a632e99c291a2ed6456dad538def8d70c791"
      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adrien-barret/claude-kit/releases/download/v0.2.5/claude-kit-v0.2.5-linux-arm64.zip"
      sha256 "eb72c51844d9da110bac3c66dba024b7c654269ef7cd58ab932f94ce2c7c89bb"
      define_method(:install) do
        bin.install "ck"
        (share/"claude-kit").install "project-template"
      end
    end
  end

  test do
    system "#{bin}/ck", "version"
  end
end
